# Game resolution (not screen resolution)
RESOLUTION_WIDTH = 360
RESOLUTION_HEIGHT = 264
HALF_RES_WIDTH = RESOLUTION_WIDTH // 2
HALF_RES_HEIGHT = RESOLUTION_HEIGHT // 2

# Game resolution for the camera
CAMERA_WIDTH = 360
CAMERA_HEIGHT = 240

# Grid sizes
GRID_WIDTH = 24
GRID_HEIGHT = 24

# General constants
TICK_RATE = 120
TARGET_FRAME_RATE = 120
SERVER_PORT = 7007
DEBUG_COMMANDS = True
